#ifndef IDONTWANTTOLEARNCMAKE_EXAMPLELIBCLASS_H
#define IDONTWANTTOLEARNCMAKE_EXAMPLELIBCLASS_H


class ExampleLibClass {
public:
    void printSuccess();
};


#endif//IDONTWANTTOLEARNCMAKE_EXAMPLELIBCLASS_H
